import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navigation/navbar";

import RegisterModal from "@/components/modals/registerModal";
import { RentModal } from "@/components/modals/rentModal";
import LoginModal from "@/components/modals/loginModal";

import ToasterProvider from "@/providers/toasterProvider";
import { SessionProvider } from "next-auth/react";
import { SearchModal } from "@/components/modals/searchModal";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <SessionProvider>
          <ToasterProvider />
          <SearchModal />
          <RegisterModal />
          <RentModal />
          <LoginModal />
          <Navbar />
          <div className="pb-20 pt-28">{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
